# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "codeScape"
description: > # this means to ignore newlines until "email:"
   on coding and sentiments around it

email: srvbhattarai@gmail.com
#blog logo
logo: "/assets/images/jekyll-logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/banner.jpg"

name: 'Saurav Bhattarai'
author: 'drklrd'
author_image: "/assets/images/jekyll-logo.png"

paginate: 5

url: "https://drklrd.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@myownprecious'

#fill in disqus shortname to use disqus
disqus: codingguffgaff

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon: twitter
    url:  https://twitter.com/myownprecious
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:  facebook
#    url: https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/drklrd
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:  google-plus
#    url: https://google.com/???
#    desc:  Add me on google+
#    share_url:
#    share_title:
#    share_link:
