'use strict';

var interests = angular.module('interests', []);




interests.interests_map = {
	"accounting" : 'accounting',
	"airport" : 'airport',
	"amusement_park" : 'amusement park',
	"aquarium" : 'aquarium',
	"art_gallery" : 'art gallery',
	"atm" : 'atm',
	"bakery" : 'bakery',
	"bank"  : 'bank',
	"bar" : 'bar',
	"beauty_salon" : 'beauty & salon',
	"bicycle_store" : 'bicycle & accessories',
	"book_store" : 'books & stationary',
	"bowling_alley" :'bowling & games',
	"bus_station": 'bus stations',
	"cafe": 'cafe',
	"campground": 'camping',
	"car_dealer": 'car deals',
	"car_rental": 'car rental',
	"car_repair": 'car repair',
	"car_wash": 'car wash',
	"casino": 'casino',
	"cemetery": 'cemetery',
	"church": 'church',
	"city_hall": 'city halls',
	"clothing_store": 'clothing and fashion',
	"convenience_store": 'convenience store',
	"courthouse": 'court',
	"dentist": 'dentist and oral health',
	"department_store": 'departmental store',
	"doctor": 'doctor',
	"electrician": 'electrician',
	"electronics_store": 'electronics & accessories',
	"embassy": 'embassy',
	"establishment": 'establishment',
	"finance": 'finance',
	"fire_station": 'fire station',
	"florist": 'florist',
	"food": 'food',
	"funeral_home": 'funerals',
	"furniture_store":'furnitures',
	"gas_station":'gas and fuel',
	"general_contractor":'contractors',
	"grocery_or_supermarket":'supermarket & groceries',
	"gym":'gym',
	"hair_care":'hair care',
	"hardware_store":'hardware store',
	"health":'health',
	"hindu_temple":'temples',
	"home_goods_store":'home good stores',
	"hospital":'hospitals & clincs',
	"insurance_agency":'insurance',
	"jewelry_store":'jewelry',
	"laundry":'laundry',
	"lawyer":'lawyer',
	"library":'library',
	"liquor_store":'liquor',
	"local_government_office":'offices',
	"locksmith":'locksmith',
	"lodging":'lodging and guesthouse',
	"meal_delivery":'meal delivery',
	"meal_takeaway":'meal takeaway',
	"mosque":'mosque',
	"movie_rental":'movies rental',
	"movie_theater":'movies theatre',
	"moving_company":'moving company',
	"museum":'museum',
	"night_club":'club',
	"painter":'painting',
	"park":'park',
	"parking":'parking',
	"pet_store":'pet stores',
	"pharmacy":'pharmacy',
	"physiotherapist":'physiotherapist',
	"place_of_worship":'worship',
	"plumber":'plumber',
	"police":'police',
	"post_office":'post office',
	"real_estate_agency":'real estates',
	"restaurant":'restaurant',
	"roofing_contractor":'roof contractors',
	"rv_park":'rv park',
	"school":'school',
	"shoe_store":'shoes',
	"shopping_mall":'shopping mall',
	"spa":'spas',
	"stadium":'stadium',
	"storage":'storage',
	"store":'store',
	"subway_station":'subways',
	"synagogue":'synagogue',
	"taxi_stand":'taxi stand',
	"travel_agency":'travel agency',
	"university":'university',
	"veterinary_care":'veterinary',
	"zoo" :'zoo'
}

